### PR TITLE
Refactoring new_tab variable to pending_tab variable in watchlist/metrics.js

### PR DESCRIPTION
**Pull request by amartinez116**
Since we have changed the name of the "new" tab to "pending" we needed to refactor the new_tab variable to "pending" to prevent any confusions in the future.

## Description

I changed the wording in the metrics files to account for the changed tab name.

## Motivation and Context

This allows us to remain consistent between the text and the name of variables in the codebase.

## How Has This Been Tested?

I have gone through and manually tested the functionalities of the metrics feature. This includes:
- able to switch between tabs
- able to update risk metrics
- resolve/contact students
- delete students from archive
- refresh watchlist
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Review by xinyis991105 — COMMENTED** [review]
In metrics_controller.rb, do we want to change the endpoint name of get_num_new_instances to get_num_pending_instances too?

**Review by xinyis991105 — CHANGES_REQUESTED** [review]
I believe the references to get_num_new_instances in view files need also be changed as well? Right now if I visit the course dashboard page it says "The action 'get_num_new_instances' could not be found for MetricsController". I believe the only place where this endpoint is accessed is in app/assessments/index.html.erb. Could you fix that?

**Comment by amartinez116** [comment]
> I believe the references to get_num_new_instances in view files need also be changed as well? Right now if I visit the course dashboard page it says "The action 'get_num_new_instances' could not be found for MetricsController". I believe the only place where this endpoint is accessed is in app/assessments/index.html.erb. Could you fix that?

Hi Xinyi, I believe that was already addressed in the last commit. I'm not getting the error, could you walk me through what you see on your end? Thanks

**Comment by xinyis991105** [comment]
Oh sorry I must have missed it then! Thanks for pointing it out!

**Review by xinyis991105 — APPROVED** [review]
LGTM!
Tested by performing regular risk metrics operations. No errors are thrown in the browser or terminal console. Display is normally rendered too. Went through all relevant files and no "new" keyword related to watchlist instances seems to remain.

**Pull request merged**
