### PR TITLE
Remove Ace Editor. Fixes #310.

### LINKED ISSUE #310: Drop Ace Dependencies
We don't use Ace anymore, so we should remove all the static files dependencies.

- [x] Delete dead code

### PR DESCRIPTION
**Pull request by jez**
Suspiciously, I didn't have to remove any dangling references from within HTML
files. The only things I removed were
- Ace library files (app/assets/javascripts/ace/*)
- app/assets/javascripts/editor.js
- app/assets/javascripts/editor.css

There weren't any Ace library CSS files, nor were there any references to Ace
or editor.{css,js} files in any of the views, at least from what I can tell.
Confirmation on this would be nice but optional I guess.

### CODE REVIEW

**Comment by jez** [comment]
"This WILL be a Ruby project when I'm done with it!" -- Dan "Dan is naD" Bucci

**Comment by dlbucci** [comment]
Aw, I wanted to merge it...

**Comment by icanberk** [comment]
Too slow, @dlbucci

**Comment by icanberk** [comment]
:love_letter:

**Comment by jez** [comment]
In other news, we're still at 58% JavaScript :( it must not change until we merge into master.

**Comment by dlbucci** [comment]
Yeah, that was something I tested when I push the slickgrid submodule branch...

**Comment by jez** [comment]
Once we get in all three of my small PRs from last night, we could probably get away with bumping the patch version. Especially considering that one of them fixes the weird Student Gradebook sizing issue (#320 )

**Pull request merged**
