### PR TITLE
Deprecate SVN

### LINKED ISSUE #785: Deprecate SVN
We need to remove all mentions of SVN from the Front-End. 

Backend code will be removed later.

### PR DESCRIPTION
**Pull request by nayak16**
Fixes #785

### CODE REVIEW

**Comment by nayak16** [comment]
@zyx-billy Do you know of any other places SVN is mentioned?

**Comment by zyx-billy** [comment]
I think there's an option to view SVN settings in the assessment#show view.

**Comment by zyx-billy** [comment]
Just did a find, there's no more SVN links. But if they had the link they could still access it. Do you think we should just remove the routes to the SVN settings page as well?

**Comment by nayak16** [comment]
Let's leave them in for now. We would get less blowback if SVN routes still work but they can no longer edit settings than if we removed them all together. Plus, it's not too urgent

**Comment by zyx-billy** [comment]
👌

**Pull request merged**
