### PR TITLE
Extension Improvements

### LINKED ISSUE #880: Wonky form inputs on extensions page
On the extensions page for an assessment, the input text fields exhibit wonky visual behavior and aren't uniform with the rest of the input fields. To recreate, go to 

http://localhost:3000/courses/AutoPopulated/assessments/lab5/extensions

and click 'Start typing student name or email'. The inputs should instead look like the input fields at 

http://localhost:3000/courses/AutoPopulated/assessments/lab5/edit

They should also have hints that are more symmetrical with those on the edit page.

screen shot 2017-06-26 at 9 31 51 pm

### LINKED ISSUE #931: Leading whitespace in user's first name breaks extension manager for that particular user.
Recently we had a case where we were unable to provide an extension to a student who has a first name field in the database containing a leading space (e.g. " P. Bouman"). While the user shows up in the user-search field in the Extension Manager, an attempt to create the extension results in a "No student with id was found for this course." error message. I was able to provide an extension by manually inserting the relevant records into the database, after which the extension did show up in the extension manager.

The problem turned out to be reproducible for all students who have a leading whitespace in their first name field. I recorded the POST data submitted by the browser for such a student, an noticed the "extension[course_user_datum_id]" part of the form data is empty. This suggest something goes wrong in creating the POST request in the browser for such students.

### LINKED ISSUE #1010: Yml does not exist: course.rb
Dear developers,

I have install Autolab usin gone-click option, then logged in as a default admin user, created a new course and assigned default admin user as Instructor for this course.

Then I went on the create an assignment and see the following as warning at the top:

** Yml does not exist: course.rb  Yml does not exist: autolab.log ** 

Indeed there were no courer.rb file in the course dir. I have copied this file from the AutoPopulated course dir, and reloaded the course config file via course manage menu. But this didn't help to get rid of the message.

Also, when I proceeded anyway with creating an assignment from tarball? the page just reloaded. 

Is there something I have done wrong? How to proceed and where to look for more tips? any log file can help me?

Reproduced with one-click setup on ubuntu18.04 and 14.04

Thanks in advance!

### PR DESCRIPTION
**Pull request by jbman223**
Fix page UI. fix characters in names. Also, fix yml not existing issues.

Fixes #931 
Fixes #1010 
Fixes #880

### CODE REVIEW

**Comment by devanshk** [comment]
Confirmed that it fixes #931, but the other two need some changes
#1010 - shows an empty error box instead of no error box
screen shot 2018-12-06 at 12 49 30 pm

#880 - form input still appears wonky
screen shot 2018-12-06 at 12 51 01 pm

**Comment by devanshk** [comment]
Looks good!

**Comment by devanshk** [comment]
Looks great!

**Comment by cg2v** [comment]
Did you test this not-on-a-mac? 
"require 'Base64'" is spelled "require 'base64'"

**Comment by cg2v** [comment]
Also, using Base64.encode64 is not safe -- it inserts newlines if more than 60 base64 characters are output. and newlines may not be part of javascript strings.
Use Base64.strict_encode64 or Base64.urlsafe_encode64 instead.

**Pull request merged**
