### PR TITLE
Remove Andrew ID from table and add indicies

### LINKED ISSUE #76: Manage accounts page: redundant AndrewID and Email columns
Delete the AndrewID column and replace it Email in the first column.

### LINKED ISSUE #77: Manage accounts page: Rows should be numbered
The rows in the Manage Accounts page should be numbered: 1, 2, 3, ... like the gradebook. 

Also, delete the ID field, which is useless to instructors.

### PR DESCRIPTION
**Pull request by Z1MM32M4N**
Fixes #76. Fixes #77.

### CODE REVIEW

**Comment by Z1MM32M4N** [comment]
Now fixes #78.

**Comment by icanberk** [comment]
Looks good!

**Comment by icanberk** [comment]
Please don't forget to close the issues

**Comment by Z1MM32M4N** [comment]
Actually, including the text "Fixes <issue>" or "Closes <issue>" in any commit closes that commit once the commit is merged. Yay for GitHub!

**Comment by Z1MM32M4N** [comment]
See <https://help.github.com/articles/closing-issues-via-commit-messages/>

**Pull request merged**
