### PR TITLE
Fixed 2 submission counting queries

### PR DESCRIPTION
**Pull request by dlbucci**
Fixes two erroneous counting queries. There may be more.

### CODE REVIEW

**Comment by ymzong** [comment]
Fixes #147?

**Comment by dlbucci** [comment]
@ymzong It should, but I'm also less than confidant that all of our queries are working as intended.

**Comment by ymzong** [comment]
Could you use a simple `grep` to search for similar queries and fix them as
well (if they exist)?

Then I'll merge it to master :)

**Comment by dlbucci** [comment]
I don't think there are any more worrisome queries of this type.

**Comment by ymzong** [comment]
@dlbucci Awesome, thanks!!

**Pull request merged**
