### PR TITLE
Restyled Edit Problem page using FormBuilder

### PR DESCRIPTION
**Pull request by Z1MM32M4N**
Makes progress towards #101 (inconsistent font sizes) and #181 (practice using
FormBuilders!).

### CODE REVIEW

**Comment by dlbucci** [comment]
This only works on the edit form and not on the new form.  Also, a breadcrumb back to problems editing page from the new/edit pages would be a nice feature, though not a requirement.

**Comment by Z1MM32M4N** [comment]
878fe56 should fix the New Problem styles, and 6cca38b should add breadcrumbs.

**Comment by dlbucci** [comment]
Could you also de-tabify the _navbar layout? Other than that, this looks good.

**Comment by Z1MM32M4N** [comment]
Do you mean the Edit Assessment tabs (basic, handin, ...), like into a single page?

**Comment by dlbucci** [comment]
No, I mean the _navbar layout has tabs instead of 2 spaces, which is why it looks all wonky.

**Comment by Z1MM32M4N** [comment]
Oh, whoops, I didn't even check the diff. Good catch; it should be fixed now.

**Pull request merged**
