### PR TITLE
Improve formatting of handin history page

### PR DESCRIPTION
**Pull request by damianhxy**
## Description
Remove unnecessary italics, introduce line breaks, improve handling of infinite extensions and add pluralization.

## Motivation and Context
As per description.

## How Has This Been Tested?
**Before**
2 days extension
Screen Shot 2022-09-24 at 14 39 58
Infinite extension
Screen Shot 2022-09-24 at 14 39 23

**After**
2 days extension
Screen Shot 2022-09-24 at 14 45 31
Infinite extension
Screen Shot 2022-09-24 at 14 45 45

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Comment by victorhuangwq** [comment]
You seemed to have swap the screenshot for the After section

**Comment by damianhxy** [comment]
> You seemed to have swap the screenshot for the After section

Fixed!

**Comment by victorhuangwq** [comment]
Could you help do a quick check on this PR https://github.com/autolab/Autolab/pull/1609 and let me know if there's any conflicts? If there isn't I will do a quick review

**Review by victorhuangwq — APPROVED** [review]
LGTM - merge if there's no conflict with #1609

**Comment by damianhxy** [comment]
> Could you help do a quick check on this PR #1609 and let me know if there's any conflicts? If there isn't I will do a quick review

Yup, no conflicts!

**Pull request merged**
