### PR TITLE
Datetime picker result display fix

### PR DESCRIPTION
**Pull request by fanpu**
## Description

Addresses #1357

## Motivation and Context

The bug comes from the fact that altInput is specified, but the formatting is not specified. Usually one would do it with altFormat, but in this case we already have a template from @oliverli that also shows the time zone as well, so I decided to go with that to be more descriptive and consistent. 

## How Has This Been Tested?

Announcement start/end times now render properly, now with the time zone being specified as well

Screenshot_select-area_20210530012825

I have also checked that handin start/end times datepicker values, and extension times still render properly. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Review by victorhuangwq — APPROVED** [review]
Tested Locally. 
LGTM!

**Comment by fanpu** [comment]
I will look at this re:Chaskiel's email on the scheduler's datepicker having issues

**Comment by victorhuangwq** [comment]
Hi @fanpu do you think this could be merged in? Seems like the recent issue with the scheduler not working could be fixed by this PR.

**Comment by fanpu** [comment]
In the ticket it seems like this is not just a display issue, but also impacts whether the values are actually persisted. We'll need to test on that front as well

**Comment by fanpu** [comment]
This PR appears to fix the issue:

```
2.6.6 :001 > Scheduler.last
  Scheduler Load (0.1ms)  SELECT  "scheduler".* FROM "scheduler" ORDER BY "scheduler"."id" DESC LIMIT ?  [["LIMIT", 1]]
 => #<Scheduler id: 1, action: "Test", next: "2021-09-08 15:53:00", interval: 10, course_id: 1, created_at: "2021-09-07 15:53:39", updated_at: "2021-09-07 15:53:39"> 
```

**Pull request merged**
