### PR TITLE
FUUUUUUUUUUUUUUUUUUUUUUUU

### PR DESCRIPTION
**Pull request by dlbucci**

### CODE REVIEW

**Comment by jez** [comment]
Dan's PR titles and branch names are always on point.

**Comment by ymzong** [comment]
That professionalism :smile_cat:

**Comment by icanberk** [comment]
how did you test this fixes DosLingos?

**Comment by dlbucci** [comment]
We were reuploading Makefile and autograde.tar, and they were getting overwritten as scp was occurring.  This was because our MD5 check wasn't working.  You need to use string keys to access the JSON values.

**Comment by icanberk** [comment]
Okay, but how do you know this fixes DosLingos?

**Comment by icanberk** [comment]
Does overwriting necessarily mean that it was breaking SCP?

**Comment by icanberk** [comment]
I'm asking because I increased the max open file limit on greatwhite like 15mins ago. That might also be the reason it's fixed.

**Comment by icanberk** [comment]
Though I still see lots of failing jobs.

**Comment by dlbucci** [comment]
Hold on, I can explain on slack.

**Comment by mihirpandya** [comment]
Please don't max open file limit. It's causing greatwhite to be really slow.

**Pull request merged**
