### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by icanberk**

### CODE REVIEW

**Comment by icanberk** [comment]
Can you guys summarize things you've change in this patch?

**Comment by icanberk** [comment]
* Improvements to the Gradesheep
* Created a page for listing the available VMs
* Improvements to the Breadcrumb navigation

**Comment by icanberk** [comment]
Anything else?

**Comment by jez** [comment]
My commits were just cosmetic:
- when you hover over a link in the gradesheet, it shows the correct mouse pointer (a pointing hand)

**Comment by dlbucci** [comment]
Small bug fixes, like moss fixes and CA submission downloads.

**Pull request merged**
