### PR TITLE
Update course#new form to use form builder

### PR DESCRIPTION
**Pull request by cjford**
Fix for #537 

Since instructor_email isn't an attribute of the course, the field can't go through the form builder. So I just wrote out the Bootstrap classes, not sure if there's any better way of doing that...

Also it didn't seem worth putting the form in a partial since it's not used anywhere else, correct me if I'm wrong though.

### CODE REVIEW

**Comment by dlbucci** [comment]
I think it's fine to add the bootstrap manually, we do that elsewhere in the codebase, but I would just use HTML for anything that isn't the text field.  we haven't used content_tags anywhere else.

**Comment by jez** [comment]
@cjford: If you could update this to use the help text from the "Course settings" page, especially as it relates to the `:name` field I could merge this. This would address the issue that was raised in #550, where it was unclear that `:name` has to be a URL-able string.

**Comment by cjford** [comment]
Added help text to name & semester fields

**Comment by jez** [comment]
Cool, thanks! I'll merge this in.

**Pull request merged**
