### PR TITLE
GDU/PLD Surfacing Improvement

### PR DESCRIPTION
**Pull request by xinyis991105**
This PR improves the surfacing of late-day/grace-day information to students when they are submitting late. It adds extra information to the academic integrity confirmation statement as well as under "number of submissions left" message. And this information does not show up if a student is not submitting late.

### CODE REVIEW

**Comment by xinyis991105** [comment]
Current phrasing:
1. "using x grace days with y additional late days"
2. If x = 0, don't show grace days at all; if grace days can cover all days late, don't show additional late days.
Proposed phrasing:
1. "submitting (x+y) days late using x grace days with y penalty late days"
Things to be confirmed:
1. Do we want to show both grace days and penalty late days regardless of the different cases? For example, if we don't have any grace days left, do we want to say "0 grace days" or not show grace days at all?
2. Are "grace days" and "penalty late days" the terms to use?
Thanks!

**Comment by victorhuangwq** [comment]
"submitting (x+y) days late using x grace days with y penalty late days"

I think the above phrasing is good. 

1. I think show depending on whether it has been used or not (if no grace days used, don't show it). So for clarification I think the cases are

**Submitting on Time** : Do not show grace days or penalty late days
**Submitting Using Grace Days**: Show grace days used
**Submitting with Penalty Late Days**: Show with how many penalty late days
**Submitting with both grace days and penalty late days**: Show both

2. Yes, it is grace days and penalty late days.

**Comment by xinyis991105** [comment]
I have updated the phrasing! Here are some screenshots of how they look for all four cases mentioned above:
Screen Shot 2020-04-09 at 11 09 40 PM
Screen Shot 2020-04-09 at 11 09 53 PM
Screen Shot 2020-04-09 at 11 10 04 PM
Screen Shot 2020-04-09 at 11 10 39 PM

**Comment by amartinez116** [comment]
Wording looks good! Small nit: change "I'm" to "I am" 

Also, in the last picture what does "(2 unpenalized, 5 total submissions left)" mean?

**Comment by xinyis991105** [comment]
It's part of the original remainingSubmissionsMsg method. I played with the settings of the assessments a little bit! It doesn't interfere with the surfacing of GDU/PLD. "I'm" has been changed to "I am"!

**Comment by amartinez116** [comment]
Small edge case, not sure if it’s something we want to worry about but what if the value of the penalty late day is zero? The message still shows up with “… with xx late penalty late days " even though there is no penalty to the grade. Do we still want to show the message?

**Comment by xinyis991105** [comment]
I think it's up to how the instructors actually use penalty late days and grace days. I would find it a bit weird if a penalty late day doesn't incur any penalty. But I would vote for still including "penalty" just to signify that the student is submitting late and using grace days is not sufficient. Also, I think the phrasing on Autolab's documentation justifies the use of possibly 0 penalty. What do other people think?
Screen Shot 2020-04-11 at 5 16 45 PM

**Comment by amartinez116** [comment]
In that case, I would agree and say that it is a good way to distinguish between grace days and penalty days (even for some reason the penalty is zero). It all looks good to me!

**Pull request merged**
