### PR TITLE
Gradebook Icon Adjustment

### PR DESCRIPTION
**Pull request by xinyis991105**
## Description
This PR changes the navigation bar gradebook icon and the gradebook link icon on the watchlist page to be consistent with the course dashboard. (Let me know if the reverse is true.)

## Motivation and Context
Currently, there is an inconsistency of icon use regarding gradebook in the top bar and the course dashboard. In addition, the icon link to a student's gradebook on the watchlist tab is also not sufficiently straightforward.

## How Has This Been Tested?
Check out any course dashboard and compare the gradebook icon with the top bar.
Check out the watchlist under metrics. The gradebook link is also now consistent with the top bar. (But I reserve my opinion on how this one should look. Is black ok? Do we want to make it a red button? Or should we leave it blue which indicates this is a link?)
Screen Shot 2021-03-16 at 5 16 27 AM
Screen Shot 2021-03-16 at 5 10 28 AM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Comment by victorhuangwq** [comment]
from the screenshot, the gradebook icon is not very top-down centred? I recommend to make it the same size as the checkbox, and center it accordingly.

**Comment by xinyis991105** [comment]
Screen Shot 2021-03-17 at 4 46 50 AM
The gradebook icon as has been re-aligned.

**Comment by victorhuangwq** [comment]
Based on the discussion during our meeting, we will not change the gradebook icon on the watchlist, but we will change the gradebook icon on the navigation bar

**Comment by xinyis991105** [comment]
Screen Shot 2021-03-18 at 4 51 38 AM
The more beautiful link icon is back.

**Review by victorhuangwq — APPROVED** [review]
LGTM

**Pull request merged**
