### PR TITLE
Assessment name shouldn't start with number #632

### PR DESCRIPTION
**Pull request by andersonleite**
Added regex validation in the assesment.rb model.

### CODE REVIEW

**Comment by dlbucci** [comment]
I think the current rails best practice is to use `validates`, rather than the special `validate_*` methods, as seen here: https://github.com/autolab/Autolab/pull/568/files

Also, why is `multiline: true`?

**Comment by andersonleite** [comment]
Hi @dlbucci 
So, how about going with this?

`validates :name, :format => {:with => /^[a-zA-Z]+$/, :multiline => true}`

Not sure why, but both with raise an error on rake autolab:update.

> bundle exec rake autolab:populate
> Creating Course AutoPopulated and config file
> Creating Assessments
> Creating Problems
> rake aborted!
> ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved

PS: :multiline - Set to true if your regular expression contains anchors that match the beginning or end of lines as opposed to the beginning or end of the string. These anchors are ^ and $.
http://api.rubyonrails.org/classes/ActiveModel/Validations/HelperMethods.html

-

**Comment by dlbucci** [comment]
Just realized this regex can is incorrect.  A course/assessment name can have numerals, they just can't begin with numerals.  The line we want is here: https://github.com/autolab/Autolab/blob/master/app/models/course.rb#L11
Also, I don't think we need or want newlines/multiple lines in assessment names.  The reason for the leading numeral restriction is that the assessment name is used to create a ruby module, and ruby module names cannot have newlines AFAIK.

**Comment by andersonleite** [comment]
@dlbucci 
Added validation line you suggested but travis build still falling. Any thoughts?

**Comment by dlbucci** [comment]
We've had issues before with forked repo pull requests not being authorized for certain steps of the build process, which causes builds to fail for non-team members.  This might be that, but another member could probably confirm.

**Comment by zyx-billy** [comment]
Yep. It seems the build failed when trying to access an environment variable. If I understood this correctly, we have [encrypted variables](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables) in our .travis.yml, which is unavailable to forked repos.

This does seem a bit inconvenient though, @ymzong, do you think it's possible to have a different build process for external pr, without having to use the github private key?

**Comment by ymzong** [comment]
@zyx-billy

Good point -- I'll patch the test script such that when the encrypted var is unavailable, the test is skipped instead of errors.

**Comment by zyx-billy** [comment]
Sounds Cool! :+1:

**Comment by andersonleite** [comment]
Thanks guys.
@ymzong 
Let me know if I need to do something more to close this PR.

**Comment by ymzong** [comment]
Thanks for the contribution @andersonleite!

**Pull request merged**
