### PR TITLE
Annotations Bonfire

### LINKED ISSUE #359: Annotations model and code should be updated
Now that we actually use the comment, value, and problem columns, we can simplify a lot of the annotations code.

### PR DESCRIPTION
**Pull request by dlbucci**
Fixes #359
Should also make new annotations viewable again.

### CODE REVIEW

**Comment by jez** [comment]
Just because it happened in this PR, is there any reason why a lot of the ruby code is 755 bs 644?

**Comment by dlbucci** [comment]
Don't know.  We actually had annotations_helper (which was empty) and annotation_helper (which wasn't being used).  I emptied the latter one function at a time until it was empty and the mv'd the name, which probably explains the permissions changing.

**Comment by icanberk** [comment]
Can we merge this to `develop`?

**Comment by icanberk** [comment]
pulled and restarted

**Comment by icanberk** [comment]
plz push to develop as well

**Comment by dlbucci** [comment]
Done.

**Pull request merged**
