### PR TITLE
No line breaks when generating base64 strings

### LINKED ISSUE #2007: Autocomplete fails for long names + email adresses
**Your environment**
Does not matter.

**Steps To Reproduce**
1. Create a user with a very long name and email address e.g. "Christopher Nathaniel Devereaux (autolab@campus.tu-berlin.de)".
2. Go to "Manage Course" -> "Act as user" -> Type <the name of the user> -> Submit.

**Current behavior**
"User does not exist in the course" flashes.

**Expected behavior**
User impersonation.

### PR DESCRIPTION
**Pull request by ugogon**
The function `strToBase64` introduces a line break (I think after every 76 character). This is incompatible with 
rails `Base64.strict_encode64` where no line breaks are introduced. This leads to the bug that the user names and email are converted to different hashes in ruby and javascript.

This PR just aligns the javascript `strToBase64` implementation with the rails `Base64.strict_encode64` implementation. _Although I still do not get why this code duplication is necessary._ 

### Summary generated by Reviewpad on 13 Nov 23 22:44 UTC
This pull request fixes a bug related to long strings in the base64.js file. The patch modifies the base64EncArr function, specifically commenting out code that adds newlines to the encoded string, since it was causing an issue.

## Description
I just commented out the lines where the line breaks are added. I think that javascript code was taken from somewhere else (as these line breaks are neither compatible with `Base64.encode64` (after 60 characters) nor `Base64.strict_encode64` (no linebreaks)) and I do not want to diverge too much from the original code.

## Motivation and Context
Fixes #2007.

## How Has This Been Tested?
Manual, see steps to reproduce in #2007.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by damianhxy** [comment]
Hi @ugogon, thanks for the PR!

The implementation was taken from https://developer.mozilla.org/en-US/docs/Glossary/Base64, but it was recently updated to a much simpler implementation in https://github.com/mdn/content/pull/25253.

If possible, it would be great if you could replace the implementation with MDN's new implementation that uses `TextEncoder`.

As for why we use base64, there is a long history behind it (starting with #931)

**Comment by ugogon** [comment]
Thanks. I updated it, although I'm not sure if a separate file is still necessary.

**Comment by damianhxy** [comment]
Either way is fine, you can leave it as a separate file for now in case another piece of code needs to use it

**Review by damianhxy — APPROVED** [review]
Tested that long names now work, and unicode names still work (e.g. chinese)

**Pull request merged**
