### PR TITLE
fixed Gemfile mimemagic contradiction

### PR DESCRIPTION
**Pull request by ugogon**
fixes https://github.com/autolab/Autolab/issues/1379

## Description
I changed the Gemfile and build the Gemfile.lock using `bundle install`

## Motivation and Context
The Gemfile demands mimemagic (>= 0.4.2) and rails (= 5.2.0) which is not possible because:

```
    rails (= 5.2.0) was resolved to 5.2.0, which depends on
      activestorage (= 5.2.0) was resolved to 5.2.0, which depends on
        marcel (~> 0.3.1) was resolved to 0.3.3, which depends on
          mimemagic (~> 0.3.2)
```
I have no idea, why this installs in the current master, but if you want to add a gem in your Gemfile or delete the Gemfile.lock the error appears.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

### CODE REVIEW

**Comment by xinyis991105** [comment]
Tested by:
1. Running "bundle install" after deleting Gemfile.lock -> works fine
2. Running "docker-compose build" using the existing Gemfile and Gemfile.lock in this PR -> image successfully built
I will have a further review of this with the team. Could you please fill in the PR details using the PR format we provide and specify which changes are university-specific? Thanks a lot!

**Comment by ugogon** [comment]
Done

**Review by xinyis991105 — CHANGES_REQUESTED** [review]
Hi Ugo! It seems the faraday gem has a newer version of 1.8.0, which is compatible with the rest of the gems. May I ask you to update that as well? Otherwise, everything seems fine! Thank you so much for your interests and support!

**Review by xinyis991105 — APPROVED** [review]
LGTM!

**Pull request merged**
