### PR TITLE
Fix the problems with adding Tweak on CUD + auto join if admin

### PR DESCRIPTION
**Pull request by icanberk**

### CODE REVIEW

**Comment by jez** [comment]
What's the general idea here? (Also, is this a WIP?)

**Comment by icanberk** [comment]
Creating a blank Tweak was causing an error and we were never saving the cud. Now we create a cud and automatically confirm the join request for an admin. (Will write something longer about how this feature works soon)

Should be merged.

**Comment by jez** [comment]
Go ahead and do it. Make sure to

- do a fast-forward merge (using the command line)
- push the update to `develop`

Then you can deploy to prod as necessary.

**Comment by dlbucci** [comment]
I don't understand why we always save the newCUD?

**Comment by jez** [comment]
Closed in favor of reverting public courses because it fixes other errors. We can come back to this with a version of public courses that's more well-tested.

**Pull request closed without merging**
