### PR TITLE
Rubocop'd A models

### PR DESCRIPTION
**Pull request by dlbucci**

### CODE REVIEW

**Comment by jez** [comment]
lol "A models"

**Comment by dlbucci** [comment]
What's funny about that?

**Comment by jez** [comment]
I was like what's an A model and the. I realized Oh, it's literally just
_everything that starts with an a_ :P

**Comment by dlbucci** [comment]
I think I know why this isn't building... I renamed "Statistics.rb" to "statistics.rb", but the OS X file system is case-insensitive, so it didn't detect the change.  So the file is still called "Statistics.rb" in the repo, despite being "statistics.rb" on my machine...

**Pull request merged**
