### PR TITLE
Fixed Ass. Stats

### LINKED ISSUE #400: Per Assignment Statistics Broken
http://i.imgur.com/g7UkOoc.png has 122 ta's instead of the correct ones?

### PR DESCRIPTION
**Pull request by dlbucci**
Not yet tested.
Fixes #400.

### CODE REVIEW

**Comment by dlbucci** [comment]
I'll test on staging once the scores migration is done.

**Comment by dlbucci** [comment]
This should work.

**Comment by jez** [comment]
Perhaps we shouldn't abbreviate Assessment to Ass. XD

**Comment by dlbucci** [comment]
Why not? Assessment is takes too long to type.

**Comment by jez** [comment]
Perhaps "Asst.'

**Pull request merged**
