### PR TITLE
Improve accessibility of Options button

### PR DESCRIPTION
**Pull request by ashleyzhang**
## Description
This PR makes the Options dropdown on the student Assignment Handin page open by default. This way, the user does not have to click into the Options button to download their handout. It also fixes a minor issue on the Instructor view where the Admin Options menu would replay the dropdown animation upon clicking the header for the first time.

## Motivation and Context
Perkins Accessibility Report recommended that we make it more clear that the Options section can be expanded.

## How Has This Been Tested?
If you navigate to any assignment, there the Options menu should start in an open state, and you'll still be able to close it by clicking on the Options header.

## Screenshots (if appropriate):
Screen Shot 2020-09-17 at 5 26 45 PM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, and here is the corresponding pull request to Autolab Docs -> 

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Review by mtoupsUNO — DISMISSED** [review]
this works for me, thanks!

**Review by xinyis991105 — COMMENTED** [review]
I tested by acting as both instructor and student. The collapsible displays correctly in both cases. But when I tab through the page, it seems that it will first focus on the whole collapsible and then on the toggle button. When the focus is on the collapsible, hitting enter does nothing. When it is on the toggle button, it toggles correctly. I tried removing the tabindex attribute from the collapsible and tabbing skips the collapsible focus. Can you look into that and see if we need to fix it?

**Comment by ashleyzhang** [comment]
Thanks for catching that! Made a change that should fix it.

**Review by xinyis991105 — APPROVED** [review]
LGTM!

**Pull request merged**
