### PR TITLE
Use uniform margin on `.card`s

### LINKED ISSUE #124: Courses don't wrap correctly when screen is resized
When the screen is resized, the spacing between courses becomes inconsistent.

Screenshot attached.

10433203_815692498477014_3528490103397129615_n

/cc @aarongut

### PR DESCRIPTION
**Pull request by Z1MM32M4N**
Commit Summary
--------------

ec652d9 (Jacob Zimmerman, 2 minutes ago)
   Stripped whitespace

cf04d88 (Jacob Zimmerman, 23 seconds ago)
   Use uniform margin on `.card`s. Fixes #124

### CODE REVIEW

**Comment by Z1MM32M4N** [comment]
The change kind of gets lost in the midst of stripping whitespace, but the real changes occur on lines 566 - 569. If you'd like a more refined diff, I separated the request into two commits so that the real changes become more apparent.

**Comment by ymzong** [comment]
From what I can observe, now `Go to Course Page` link appears (vertically) at the bottom of its row, instead of at the middle.

**Comment by Z1MM32M4N** [comment]
I don't quite know what you mean, could you post a screenshot?

**Comment by ymzong** [comment]
Sure:

screenshot from 2015-01-18 21 33 09

**Comment by Z1MM32M4N** [comment]
I can't reproduce this. I'm on Chrome on a MacBook Air. I'm testing the change locally (with the actual patch applied) as well as on autolab.cs.cmu.edu (by applying my change from the Inspector. I just pulled.

The only thing I can think is that you're either running an out-of-date version of the code base, have some other local changes that affect this, or are using a different browser. Any other ideas?

Either way, I think that the button being at the bottom is less visually distracting than the cards not wrapping correctly.

**Comment by icanberk** [comment]
Yeah, it happens for me too sometimes. But I think we can fix the smaller bugs later.

**Pull request merged**
