### PR TITLE
Add rubocop pre commit hook

### PR DESCRIPTION
**Pull request by Huahan98**
## Description

Add rubocop precommit hook with overcommit. 
 
## How Has This Been Tested?

First need to install overcommit: `gem install overcommit`
Then you could run linting explicitly with 'overcommit --run", or it will be run before commits:

Screen Shot 2022-02-17 at 5 28 08 PM

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Comment by victorhuangwq** [comment]
image
This is the error that is given to me. 

Also could you add the gem to the gemfile? Under group:development

**Comment by Huahan98** [comment]
> 
yeah you need to run `overcommit --sign` like the message says, this only needs to be run once. 

Added `overcommit` to Gemfile.

**Comment by victorhuangwq** [comment]
you have to add quotes around overcommit haha

**Comment by victorhuangwq** [comment]
Okay I have added it

**Comment by victorhuangwq** [comment]
Overcommit does not run when I do a git commit

**Comment by Huahan98** [comment]
Update: 
please run `overcommit --install && overcommit --sign` under Autolab/ to init overcommit (this only needs to be run once).

**Comment by victorhuangwq** [comment]
Tested by making a faulty commit. Works as intended. LGTM

**Review by victorhuangwq — APPROVED** [review]
LGTM

**Review by victorhuangwq — DISMISSED** [review]
LGTM

**Review by victorhuangwq — APPROVED** [review]
LGTM

**Pull request merged**
