### PR TITLE
Removal of Text Column from Annotations Table and Other Legacy files

### LINKED ISSUE #1190: Deprecate `text` column on annotations table
It appears that the `text` column on the annotations table is not being used anywhere anymore and is probably legacy. We can consider removing the column to save space and reduce confusion

### PR DESCRIPTION
**Pull request by xinyis991105**
This PR addresses issue #1190. The unused 'text' column of annotations is removed along with other legacy files.

## Description

1. A migration file that removes 'text' column from annotations is added to db/migrate.
2. The requirement for 'text' to be present in app/controllers/annotations_controller.rb is removed.
3. app/views/scores/_score.html.erb and app/views/scores/show.html.erb are removed, as their functionality is achieved through app/views/assessments/viewFeedback.html.erb.
4. app/helpers/annotations_helper.rb is removed since it only contains an empty declaration for a module called AnnotationsHelper which is not used anywhere.

## Motivation and Context

This change is required as it will save space for our project. This PR will close #1190.

## How Has This Been Tested?

Before making the changes, I've searched the project for the keyword 'annotation'. In these files, I searched again for the keyword 'text'. After that, I've made changes accordingly. I've tested my changes by visiting pages that potentially requires the text column of annotations (assessment score feedback, assessment handin history, handin file inspection). No error is shown in the browser. In addition, all feedback pages are rendered through app/views/viewFeedback.html.erb. Double check is needed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, and here is the corresponding pull request to Autolab Docs ->

### CODE REVIEW

**Review by amartinez116 — COMMENTED** [review]
Looks good! Since you are modifying the database also check in db/schema.rb

**Comment by xinyis991105** [comment]
@amartinez116 Do I need to manually change the schema.rb file since it's just removal of a single column or should I run migration first and update with the auto-generated file? A problem with running migration on my end is that my local database contains tables for the csv mapping branch so doing so actually adds unnecessary information to this branch. Do you know of any method to avoid this or should we wait until we collectively migrate sometime in the future?

**Comment by amartinez116** [comment]
@xinyis991105 oh I see! When I run migration on my end I just get the changes for removing the "text" string element. In that case then we can wait until we collectively migrate in the future.

**Review by amartinez116 — APPROVED** [review]
LGTM. Successfully tested on my end as well.

**Pull request merged**
