### PR TITLE
Fixed Autolab:Populate

### PR DESCRIPTION
**Pull request by dlbucci**

### CODE REVIEW

**Comment by icanberk** [comment]
did we test this? I feel like we are also required to add a `assessment.quizData` field

**Comment by andrewwuan** [comment]
There's a category_id field that we need to take care of

**Comment by dlbucci** [comment]
@icanberk: quizData is no longer required, and probably shouldn't be, as most assessments aren't quizzes (we could validate it's presence for quiz assessments, but it's not necessary at the moment).
@andrewwuan: category_id just got removed, because we removed the assessment_category model, which is why the script broke.

**Comment by icanberk** [comment]
@dlbucci when did we make quizData not required? (I know we should but I just haven't seen the commit)

**Comment by dlbucci** [comment]
Here? a83f89df94214346add8da2569355c8eb538bb75

**Comment by icanberk** [comment]
Magic. Okay.

**Comment by andrewwuan** [comment]
@dlbucci Have we migrated it yet? I still see `category_id` in db/schema.rb

**Comment by dlbucci** [comment]
Yeah schema's a little out of whack.  If you migrate it, category_id should be removed.

**Pull request merged**
