### PR TITLE
Fixed and cleaned up methods for log and local submissions

### PR DESCRIPTION
**Pull request by icanberk**

### CODE REVIEW

**Comment by icanberk** [comment]
This should not be merged yet, but I wanted to push it to get your comments.

**Comment by icanberk** [comment]
This is up for review now

**Comment by dlbucci** [comment]
How well has this been tested? We seem to still be getting error reports.

**Comment by icanberk** [comment]
I think those errors were from while I was developing.

**Comment by dlbucci** [comment]
The ones mentioned at the end of #126?

**Comment by icanberk** [comment]
Gonna work on those soon.

**Comment by dlbucci** [comment]
Alright, well I don't think we're any worse off with this in then, so I'll merge.

**Pull request merged**
