### PR TITLE
Refactor long functions in asmt,courses controller

### PR DESCRIPTION
**Pull request by ymzong**
This code mainly refactors long functions in `AsmtController` and `CoursesController`. 

Regarding #397: This PR only refactors the current code instead of switching to `Archive` library in `#importAsmtFromTar`. This is because the library would not make the code cleaner, and instead I would need to pre-process import tarball in order to use the library. I'd like to fix all `Archive` issues together in another PR.

### CODE REVIEW

**Comment by dlbucci** [comment]
Did you run rubocop on these files?  You don't have to clean the entire files, but it would help cleanup the functions you're refactoring.

**Comment by ymzong** [comment]
@dlbucci No I didn't run rubocop on the files. How would I run it on individual functions?

Also, probably you can do `rubocop`ping in a separate PR?

**Comment by dlbucci** [comment]
You can run it on the files, but only correct it in the functions you change.

**Comment by ymzong** [comment]
Just `rubocopped`!

**Pull request merged**
