### PR TITLE
Fix External Tar Bug

### PR DESCRIPTION
**Pull request by dlbucci**

### CODE REVIEW

**Comment by ymzong** [comment]
Did you test this? How external moss works is like this: inside `external.tar`, there can be:
- `submission1/`
- `submission2.tar`
- etc.

And, we need to add `externalTarDirectory/**/*` to MOSS command.

**Comment by dlbucci** [comment]
It's tested and works, but it no longer works for nested archives.

**Comment by ymzong** [comment]
@dlbucci I'll complete the fix now, if you are not working on it

**Comment by dlbucci** [comment]
What's there to complete? Nested archives aren't really very feasible, and we already specify that on the moss page.

**Comment by ymzong** [comment]
I want to refactor the code a bit -- the current function is too long

**Comment by dlbucci** [comment]
You mean runMoss?  It could be split into a few functions.  If you want to do that, go for it, but since this is a hotfix, can we merge and do that in develop?

**Comment by ymzong** [comment]
Oh definitely, go ahead!

**Pull request merged**
