### PR TITLE
Fix quiz + Assessment Builder

### PR DESCRIPTION
**Pull request by icanberk**

### CODE REVIEW

**Comment by andrewwuan** [comment]
I got "Validation failed: Category name can't be blank" when I tried to create a quiz...

**Comment by icanberk** [comment]
I'm still working on this. Just pushed to test on staging. Biggest problem right now is that it doesn't create the directory and I haven't figured out why yet.

**Comment by icanberk** [comment]
Also discovered lots of problems with Assessment builder. Fixing them as well

**Comment by andrewwuan** [comment]
Do you want me to work on this? I planned to do it tomorrow...

**Comment by icanberk** [comment]
hey @andrewwuan, that'd actually be great. I had some progress but then got sidetracked by Assessment builder. you can keep working on this branch.

I think two things are left: (1) It doesn't create the directory so it raises an error (2) category should allow creating new categories and also should not fail validation if new category field is empty.

**Comment by andrewwuan** [comment]
@icanberk sounds good! I'll work on it tonight

**Comment by andrewwuan** [comment]
@icanberk I've resolved the two issues you mentioned. Let me know if there's more I can help!

**Comment by icanberk** [comment]
It looked good to me otherwise. Have you tested take quiz page?

**Comment by icanberk** [comment]
I didn't play around with that part much since I wasn't able to create good quizes.

**Comment by andrewwuan** [comment]
Working on it!

**Pull request merged**
