### PR TITLE
Exception Notifications for no-view routes

### LINKED ISSUE #491: We should be notified if no-view routes fail
Specifically, local_submit, log_submit, and autograde_done should be sending us emails if they fail, which doesn't happen because we (correctly) catch the errors before the global render_error function is called.

### PR DESCRIPTION
**Pull request by dlbucci**
Fixes #491 
This mucks with handin and autograding code, so test it out.  I checked and regular handins seemed to work fine with autograded assessments using polling for the autograding.  We should test the autograde_done callback on staging.

### CODE REVIEW

**Comment by jez** [comment]
@dlbucci What's the state of this PR, does it work?

How can I test it?

**Comment by dlbucci** [comment]
It should work/shouldn't have a noticeable effect, except we'll get error emails and messages.  You can probably test that handin and autograding still works by pulling this to staging and testing there.

**Comment by dlbucci** [comment]
Can we also get this into v1.7.0?

**Comment by dlbucci** [comment]
PING

**Comment by nayak16** [comment]
Deprecated

**Pull request closed without merging**
