### PR TITLE
Initial Work on Datetime Pickers

### PR DESCRIPTION
**Pull request by Z1MM32M4N**
### Commit Summary

c279e97 - Purge all date & time assets

76b10b8 - [bundle install] Add date time dependencies

You will need to run

    bundle install

after merging this commit.

76c1e75 - Stripped whitespace from application_helper.rb

b400e3d - Remove duplicate version of jQuery (#225)

c9249e5 - Use Bootstrap grid over manual width styling

Also edited create_edit.css.scss for SCSS style guidelines.

38c7733 - Incorporate Bootstrap 3 Datetimepicker (#181)

Functionality Added

 - The custom form builder `FormBuilderWithDateTimeIntpu` adds support
   for date selectors to be added with `f.date_select` and
   `f.datetime_select`.
 - The Edit Assessment > Handin page was refactored to use the above
   functionality
 - The `initialize_datetimepickers.js` file contains the logic needed
   to initialize any datetime picker on any page. It still needs to be
   included whenever datetimepickers will be on the page.

Notable Additions

 - Removes commented out code relating to Waves.js
 - Loads moment.js and bootstrap-datetimepicker.{css,js} on all pages
   the using application.{css,js} files.

7e3eb77 - Patch styles for Bootstrap 3 Datepicker (#181)

### CODE REVIEW

**Comment by Z1MM32M4N** [comment]
These changes have been tested to work for the Edit Assessment > Handin page.

Currently, the only line items of #181 that this doesn't resolve are linked date pickers (which is slightly more complicated because we have four fields which need to be arranged chronologically, not two) upgrading all date pickers (the framework is there, but not the changes nor testing).

**Comment by icanberk** [comment]
This is cool.

Are the icons at the bottom of the picker coming from the library? They will probably be a little confusing to the users. Can we add "Current Date" and "Set Time"/"Set Date" texts next to them?

**Comment by icanberk** [comment]
@Z1MM32M4N if it's going to require too much work, we can leave it for the later versions. Just let me know. I really want to close the issue this weekend :)

**Comment by Z1MM32M4N** [comment]
I might be able to hack it together. I was pouring over the source to
figure out what classes to style, so I have a few ideas. Certainly I could
do it by forking the project, but I might be able to get it with even less
work.

**Comment by icanberk** [comment]
Forking the project is probably unnecessarily too much work at this point.

Maybe you can add content to an :after class...

**Comment by Z1MM32M4N** [comment]
Yep, that's exactly what I had in mind.

**Comment by Z1MM32M4N** [comment]
This should be good to go.

**Pull request merged**
