### PR TITLE
Feature debugging gems

### PR DESCRIPTION
**Pull request by dlbucci**
I'm creating this for people to see what running rubocop looks like.  The auto-correct turned 7000 errors into 1700.

### CODE REVIEW

**Comment by dlbucci** [comment]
For an example of configuration settings we can change in the future:
https://github.com/bbatsov/rubocop/blob/master/config/default.yml
Also, I have not tested this, so it's not 100% certain all code still works (not that we're ever certain of that *cough*).

**Comment by icanberk** [comment]
Do you want me to test this on staging?

**Comment by dlbucci** [comment]
Yeah.  It's a lot of changes and the rubocop repo said auto-correct was experimental, so the results might not be accurate.

**Comment by icanberk** [comment]
/opt/autolab3/build/autolab-src/app/controllers/application_controller.rb:111: syntax error, unexpected $undefined, expecting keyword_end
        " please contact the Autolab Development team at the " \ 
                                                                ^ (SyntaxError)

**Comment by dlbucci** [comment]
Don't know why it did that...

**Comment by dlbucci** [comment]
I'll look into fixing these issues later.

**Comment by ymzong** [comment]
@dlbucci: The issue @icanberk mentioned was fixed -- it was because there was a trailing writespace after one of your backslashes, and Ruby doesn't like it.. :smile:

**Comment by icanberk** [comment]
It's easy to fix... but I'm worried that there are a lot more of those.

**Comment by ymzong** [comment]
Oh wait, that changed was caused by `rubocop`? I thought Dan changed it manually...

**Comment by dlbucci** [comment]
That's why we should check every page and tes this thoroughly. I can't
believe ruby wouldn't allow that...

If only we had a systematic way to test that every page was working...

**Comment by ymzong** [comment]
Well, the testing framework can kind of do that, but I still can't guarantee 100% coverage.

**Comment by dlbucci** [comment]
So do we want to merge this?  It has to happen at some point and if we put any sweeping changes in before, it's just gonna turn into a bear.

**Comment by icanberk** [comment]
Did anyone check if there are any more whitespaces after one of backslashes?

**Comment by icanberk** [comment]
There seems to be more of the same errors

**Comment by dlbucci** [comment]
There's at least one other place, I'll try to fix it now.  If we can get the server to start, should we merge?

**Comment by icanberk** [comment]
Yeah I want to merge it

**Comment by icanberk** [comment]
We good?

**Comment by dlbucci** [comment]
Sawshark's a-running, and there don't seem to be obvious errors.

**Pull request merged**
