### PR TITLE
Move documentation to wiki

### PR DESCRIPTION
**Pull request by jez**

### CODE REVIEW

**Comment by jez** [comment]
@icanberk are we good here? This is just a change to the README.

**Comment by icanberk** [comment]
I'm not sure about this. I feel like it's still good to have a quick start on the main page or at least doesn't hurt. @dlbucci, @ymzong, @andrewwuan what do you guys think?

**Comment by jez** [comment]
The only think is that it fragments the documentation, making it easy to get out of date, but I can definitely see the appeal to having something in the README.

**Comment by dlbucci** [comment]
I like having the getting started in the documentation.  Most projects seem to have something similar.

**Comment by jez** [comment]
By "documentation," do you mean README or wiki?

**Comment by dlbucci** [comment]
README, sorry.

**Comment by icanberk** [comment]
I feel like I look for that section whenever I'm taking a look at a project's README,.

**Comment by dlbucci** [comment]
Absolutely.  Our starting section is a bit larger than usual, but it's sort of complex to start using Autolab.  Maybe the wiki can go into more detail with common issues or something?

**Comment by icanberk** [comment]
I agree with that starting section. I think after we publish the first blog post, we can shorten that intro part and link to the blog.

**Comment by jez** [comment]
I guess I was trying to model our README after what the [Neovim](https://github.com/neovim/neovim) project does. They have a short summary of the goals of the project, and then they pull out the important questions that people would be asking and answer them with wiki posts that they link to.

I definitely think the blog post will complement this, because we can have a short-and-sweet summary, a link to the introductory post, and then an FAQ to get people started.

**Comment by dlbucci** [comment]
As part of this, we should remove the ./doc folder from the repo.  It's hysterically out of date.

**Comment by jez** [comment]
We can resume this discussion again some other time. For now, since no progress is being made and most people are working on other things, I'm closing this PR.

**Pull request closed without merging**
