### PR TITLE
SVN now affects submissions

### PR DESCRIPTION
**Pull request by dlbucci**
I will test this more when it's not 3:18am, but Autolab will now do SVN validations and attempt to checkout work instead of just pretending that an SVN submission is a normal submission.

More work needs to be done, specifically for groups, which I'm 80% certain won't work quite the way users would expect them to (currently, they checkout every users own repository, vs sharing the repo of the submitting user).  I'll fix that at some point.

### CODE REVIEW

**Comment by jez** [comment]
@dlbucci I don't know enough about how this part of Autolab works to test this at all.

**Comment by dlbucci** [comment]
We should probably merge this in before v1.7.0, or with v1.7.0

**Comment by icanberk** [comment]
@dlbucci how can we test this? I have no idea either :/

**Comment by dlbucci** [comment]
Write an assessment config module with a `checkoutWork(fromDir, toDir)` that somehow moves files in the `fromDir` to the `toDir`.  Click checkout and make sure the files in the `fromDir` wind up in the handin tar.

**Comment by dlbucci** [comment]
PING

**Comment by remzr7** [comment]
Removing SVN and hence closing issue

**Pull request closed without merging**
