### PR TITLE
Improvements to gradesheet

### PR DESCRIPTION
**Pull request by icanberk**
Please don't ask me why or how this works.

### CODE REVIEW

**Comment by icanberk** [comment]
1) Creates larger text areas for feedback
2) Saves when the TA closes the box without pressing save.

**Comment by icanberk** [comment]
@jez you should just git pull and test it manually.

**Comment by dlbucci** [comment]
Why or how does this work?

**Comment by dlbucci** [comment]
Wait, did you switch to the backbone gradesheet?  If so, there's a corresponding gradesheet2.html.erb we should probably be using.

**Comment by icanberk** [comment]
I didn't switch to backbone?

I just renamed gradesheet1 to gradesheet. 

I think I should get rid of gradesheet2.html.erb. What do you say?

**Comment by icanberk** [comment]
Where did you see Backbone?

**Comment by dlbucci** [comment]
Oh, the old gradesheet.js file was the JS for gradesheet2.html (sane, right?), which was a backbone gradesheet we never used in production.  That's what you deleted.  So yes, I would get rid of gradesheet2.html.erb if we are never going to use it.

**Comment by icanberk** [comment]
Can someone test this?

**Comment by dlbucci** [comment]
I sort of fail to see why that binding change would affect anything.

**Comment by dlbucci** [comment]
Gotcha.

**Comment by icanberk** [comment]
It's also good because if we dynamically add rows after initial load, it will still work.

**Comment by jez** [comment]
We should set `cursor: pointer;` on the email links or set `href="#"` so that Chrome uses a pointing hand rather than a text-editing cursor.

**Comment by jez** [comment]
Other than that, it looks like this is solid :+1:

**Comment by icanberk** [comment]
thanks for taking care of this.

**Comment by icanberk** [comment]
:100:

**Comment by jez** [comment]
#teamwork :P

**Comment by dlbucci** [comment]
@icanberk Didn't you combine the email and name columns? I'm not seeing that when I run develop on my machine.

**Pull request merged**
