### PR TITLE
Improve attachments interface and error handling

### PR DESCRIPTION
**Pull request by damianhxy**
## Description
- Add "add attachment" button to view course page
- Move "add attachment" button to top when viewing an assessment
- Make "add attachment" button same height as attachments list items
- Redirect to course page instead of course attachments page after adding / updating a course attachment
- Prevent internal server error if an error occurs while creating an attachment
- Remove dead attachment code
- Make course attachments list UI consistent with assessment attachments (i.e. clickable icon, shows not released if applicable) -- see comments for elaboration
- Make attachments list page UI consistent with course / assessment attachments list -- see comments for elaboration

## Motivation and Context

Attachments can be added directly when viewing an assessment, but not when viewing a course (have to access Manage Course > Manage course attachments). Also, the add "attachment list" list item has a different height as compared to the other list items.

Screenshot 2023-01-10 at 12 56 05
Screenshot 2023-01-10 at 12 56 15

Furthermore, if an error occurs when creating an attachment, we get an error

Screenshot 2023-01-10 at 12 59 28

This is because `create` calls `update`, which attempts to redirect to the edit attachment page if the update fails. But if we were creating to begin with, the attachment doesn't exist yet, so we get the error.

## How Has This Been Tested?

**UI CHANGES**
- Attachments can now be created directly from the view course page.
Screenshot 2023-01-10 at 13 01 04

- Furthermore, the "add attachment" button is moved to the top to make it easier to add new attachments.
Screenshot 2023-01-10 at 13 01 13

- Ensure that the "add attachment" buttons show up both with and without existing attachments.
- Ensure that the "add attachment" list item is now the same height as the other list items (i.e. the attachments).

**LOGIC CHANGES**
- Successfully create a course attachment, and an assessment attachment
Screenshot 2023-01-10 at 13 10 52
Screenshot 2023-01-10 at 13 07 47

- Successfully update a course attachment, and an assessment attachment
Screenshot 2023-01-10 at 13 11 05
Screenshot 2023-01-10 at 13 07 33

- Unsuccessfully create a course attachment (e.g. remove required attribute on name field and leave field blank / not upload a file)
Screenshot 2023-01-10 at 13 04 12

-  Unsuccessfully create an assessment attachment
Screenshot 2023-01-10 at 13 05 04

- Unsuccessfully update a course attachment
Screenshot 2023-01-10 at 13 06 47

- Unsuccessfully update an assessment attachment
Screenshot 2023-01-10 at 13 05 42

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

### CODE REVIEW

**Review by 20wildmanj — APPROVED** [review]
Followed testing plan successfully, LGTM.

Since this PR improves the attachments UI, could you also make course attachments visually look the same and act the same as assessments?

Screen Shot 2023-01-11 at 10 52 47

Both attachments are unreleased, but only the assessment specific one displays that to the instructor. Also, the download button doesn't have a hyperlink for the course attachment.

**Comment by damianhxy** [comment]
Appearance is now consistent

Screenshot 2023-01-10 at 22 07 54

**Comment by damianhxy** [comment]
I've also made the appearance of the attachment list page consistent

Note: the assessment attachment list page isn't linked anywhere, but you can access it by appending a "/attachments" to the URL, e.g. `http://localhost/courses/syntax-error/assessments/twosumlab/attachments`

**Before**

Screenshot 2023-01-10 at 22 16 04

Screenshot 2023-01-10 at 22 16 16


**After**

Screenshot 2023-01-10 at 22 15 41

Screenshot 2023-01-10 at 22 15 48

**Comment by 20wildmanj** [comment]
Appearance looks consistent for course attachments and assessment attachments, and manage attachments with the other pages. LGTM

**Pull request merged**
