### PR TITLE
Move AutogradingSetup into its own controller

### PR DESCRIPTION
**Pull request by dlbucci**
Don't think this is ready for primetime yet, but what do you guys think?

### CODE REVIEW

**Comment by jez** [comment]
What's the idea behind this feature?

**Comment by dlbucci** [comment]
Clean up, mostly. Our assessments_controller is HUGE, and autograding settings code really doesn't belong there, so this scales it back.

**Comment by icanberk** [comment]
what if we got rid of autograding_setups completely and add columns to assessment table?

Current attributes are:
```
    t.integer "assessment_id",     limit: 4
    t.integer "autograde_timeout", limit: 4
    t.string  "autograde_image",   limit: 255
    t.boolean "release_score",     limit: 1
```

**Comment by dlbucci** [comment]
I think the assessments table is complex enough already, plus more than half of our assessments don't use autograding, so that would be a bit of wasted space.

**Comment by dlbucci** [comment]
This should be ready for showtime/testing.

**Comment by icanberk** [comment]
I pulled this on sawshark and migrated. Seems like autograde roundtrip is working.

**Pull request merged**
