### PR TITLE
Feature rspec

### PR DESCRIPTION
**Pull request by icanberk**
I made this so that I can watch changes.

### CODE REVIEW

**Comment by ymzong** [comment]
Cool cool, but don't merge yet :smile:

**Comment by icanberk** [comment]
```
bundle exec rake spec

/Users/ican/.rbenv/versions/2.2.0/bin/ruby -I/Users/ican/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib:/Users/ican/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-support-3.2.2/lib /Users/ican/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
I, [2015-03-16T11:24:50.212091 #18259]  INFO -- : Not reporting to Code Climate because ENV['CODECLIMATE_REPO_TOKEN'] is not set.

```

Can CODECLIMATE_REPO_TOKEN become a config field or something?

**Comment by icanberk** [comment]
Also, what are we exactly using CODECLIMATE for?

**Comment by icanberk** [comment]
In @ymzong we believe.

**Comment by ymzong** [comment]
@icanberk https://travis-ci.org/autolab/Autolab/builds/54663726

**Pull request merged**
