### PR TITLE
Two Simple Fixes

### PR DESCRIPTION
**Pull request by dlbucci**
Fix admins#show markup.
Validate for no leading numerals in courses.

### CODE REVIEW

**Comment by ymzong** [comment]
LGTM!

**Comment by nayak16** [comment]
Is this a fatal build failure bc of this PR's changes or is it something else?

**Comment by ymzong** [comment]
Travis test passed at last!
It was due to an insecure RegEx pattern introduced in this PR.

**Comment by nayak16** [comment]
Interesting. Good to know the test is very thorough

**Pull request merged**
