### PR TITLE
Add emails to watchlist

### PR DESCRIPTION
**Pull request by ashleyzhang**
## Description
This PR changes the metrics feature watchlist to add student email addresses directly below student names in small grey font.
Screen Shot 2021-04-11 at 11 00 55 PM

## Motivation and Context
Since instructors often search for students based on the student IDs associated with their emails, we want to make student emails visible in the watchlist.

## How Has This Been Tested?
The email address should always appear directly below the student's name.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Comment by victorhuangwq** [comment]
Thanks for the quick work! Looking at the screenshot I'm wondering if it would look better if the checkbox on each instance is top down centered?

**Comment by ashleyzhang** [comment]
Good point, I agree - here's how it looks now!
Screen Shot 2021-04-12 at 11 00 22 AM

**Comment by victorhuangwq** [comment]
I think this looks okay. @amartinez116 can you weigh in as well?

**Comment by amartinez116** [comment]
I think it looks good! 
Nit: in the gradebook we made the emails clickable and that leads to the same link as our icon (student's gradebook). Not sure if we want to pick consistency over clarity?

**Comment by ashleyzhang** [comment]
> Nit: in the gradebook we made the emails clickable and that leads to the same link as our icon (student's gradebook). Not sure if we want to pick consistency over clarity?

Ooh that's definitely a good point - but I actually think it's better as is, solely because the name and email are labels on the checkbox, which means that clicking the name or email also checks the checkbox. It might be a little frustrating if going to the gradebook caused the checkbox to be clicked as well. We could change it so that clicking the name and email doesn't affect the checkbox, but that'd significantly reduce the size of the clickable area.

Although I do think it'd look better than having the current outgoing link icon for the gradebook... open to more feedback!

**Comment by victorhuangwq** [comment]
My personal opinion is that this is good for now. With our watchlist instance I don't think we need them to click into the gradebook often anyways

**Comment by amartinez116** [comment]
Sounds good to me, we can leave it as is.

**Review by victorhuangwq — APPROVED** [review]
LGTM!
Tested Locally

**Pull request merged**
