### PR TITLE
Remove max score check from gradesheet

### LINKED ISSUE #836: Leaving Max Score for a Problem blank breaks entering scores in gradesheet
Leaving max score blank no longer allows inputting a grade that's higher than the problem's max score, because max score defaults to 0. 

This check should be bypassed when entering scores in the gradesheet

### PR DESCRIPTION
**Pull request by nayak16**
Fixes #836

### CODE REVIEW

**Comment by zyx-billy** [comment]
Looks good to me! Basically reverted to what it was before 2.0 I guess.
One weird thing though: We didn't used to set score during `quickSetScoreDetails` ([this line](https://github.com/autolab/Autolab/blob/master/app/controllers/assessment/grading.rb#L295) was added in 2.0). There's a [comment](https://github.com/autolab/Autolab/blob/master/app/assets/javascripts/gradesheet.js.erb#L470) mentioning this in the gradesheet js. Do you know why it was set this way? It seems to work perfectly fine to me.

**Comment by nayak16** [comment]
Hmm that is strange. I left the line in `quickSetScoreDetails` and it was still giving `422` error. Somewhere `quickSetScoreDetails` is still being called.

**Comment by zyx-billy** [comment]
oh what I meant was before 2.0 we weren't using the score parameter in quickSetScoreDetails. In 2.0, we started using the score parameter, and also added in the max score check. It was right to remove that check in quickSetScoreDetails, but I'm not sure if we should also keep [the line](https://github.com/autolab/Autolab/blob/master/app/controllers/assessment/grading.rb#L295) that uses the score parameter.

**Comment by nayak16** [comment]
Yeah that line is just superfluous actually

**Pull request merged**
