### PR TITLE
Watchlist functionality integration with endpoints

### PR DESCRIPTION
**Pull request by amartinez116**
## Description

Watchlist now obtains necessary information from the API and displays it. (Styling will be handled in front-end PR). 
Correct student information goes to the designated side tab (new, contacted, resolved, archived). 

image

## Motivation and Context

In order to integrate API endpoints with watchlist front end to have full working functionality. 

## How Has This Been Tested?

Tested locally by setting up different risk metric parameters and having the watchlist information update in real time. 
There are different scenarios which are accounted for:
1) Risk metrics have not been set up. Therefore we view the unidentified metrics message:
image
 
2) Risk metrics have been set up but no students are identified in the current sidetab:
image

3) Risk metrics have been set up and students have been identified: 
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

The following still need to be handled:
- Selected students to contact/resolve and pass their instance_ids to $('#contact_button').click() and  $('#resolve_button').click() functions
- Refresh watchlist when an instructor updates grades
- Same student appears multiple times with different violation tags. Need to condense same student into one row.

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Comment by xinyis991105** [comment]
Tested by:
1. Set metrics to nothing. The "undefined conditions" message is rendered correctly.
2. Set metrics to ridiculous condition such that no watchlist instance has to be added. The "no student" message is rendered correctly.
3. Set metrics to something more appropriate such that watchlist instances are added. Students' information along with their email and violated risk condition's type are shown correctly.

Just want to make sure before I approve this:
1. The contact and resolve functionality will be added in subsequent PRs, is that correct?
2. I have two little problems in the risk metrics tab where 1) if I change the date of the grace day usage condition, the save button doesn't seem to be turned on to allow for clicks. 2) The number of consecutive assignments in the grade drop rule seems to be limited to 2 only. Are those expected?

Otherwise, LGTM!

**Comment by amartinez116** [comment]
As per your questions,

1) I decided to include contact and resolve functionality in this PR. Currently it will depend on the front end PR that Ashely is working on to obtain the selected rows of students and their instance_ids but if you hard code values for ids in lines 297/303 then the functionality should work!
2.1) Good catch! Turned out to be some weird fomantic Ui issue. Should be fixed now.
2.2) The max number of consecutive assignments in the grade drop rule seems has to do with the number of max_consecutive_assessments (not inclusive since we are comparing between assignments). While 2 is the minimum number of assignments that we can compare. Can you double check the max_consecutive_assessments number for the course you tested it out on.

**Comment by amartinez116** [comment]
1. I decided to include contact and resolve functionality in this PR. Currently it will depend on the front end PR that Ashely is working on to obtain the selected rows of students and their instance_ids but if you hard code values for ids in lines 297/303 then the functionality should work!

2.1. Good catch! Turned out to be some weird fomantic Ui issue. Should be fixed now.

2.2. The max number of consecutive assignments in the grade drop rule seems has to do with the number of max_consecutive_assessments (not inclusive since we are comparing between assignments). While 2 is the minimum number of assignments that we can compare. Can you double check the max_consecutive_assessments number for the course you tested it out on.

**Review by xinyis991105 — APPROVED** [review]
1. Tested out contact and resolve by hardcoding id values. Clicking on contact and resolve buttons work as expected.
2. Changing grace day usage date now turns on submit button correctly.
3. I believe for the course I'm testing with, the maximum number of consecutive assessments is 3. We can take a note of this and have another look in later PRs!
Otherwise, LGTM!

**Pull request merged**
