### PR TITLE
Unlimited multipart

### PR DESCRIPTION
**Pull request by dlbucci**
Should fix the server errors that moss has been causing.  Also updates a config file to be a template, so that change will need to be made during the pull to production.

### CODE REVIEW

**Comment by icanberk** [comment]
pulled to prod.

**Comment by jez** [comment]
Should `config/initializers/devise.rb.template` have been .gitignored?

**Comment by dlbucci** [comment]
No, but config/initializers/devise.rb should have.

**Comment by jez** [comment]
Whoops, yeah that's what I mean. It's not being ignored currently.

**Comment by dlbucci** [comment]
Right, if you want to commit that change develop right now, go for it.

**Pull request merged**
