### PR TITLE
Add Autograder Output to Speedgrader

### PR DESCRIPTION
**Pull request by victorhuangwq**
## Description

This allows graders to easily grade / refer to autograder output without opening a new tab.

## Motivation and Context

From interview with teaching assistants.

## How Has This Been Tested?

Single file autograded submission
image

Archived autograded submission
image

Single file autograded submission
image

Archived non-autograded submission
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Review by fanpu — DISMISSED** [review]
Code looks good, tested working with hello lab on my setup!

**Comment by fanpu** [comment]
The 'Download File' button results in error when clicking on it with the autograder output as the selected file. I don't think it's a big deal, we can just add it as a TODO somewhere. We could also case on position to not show that button when the autograder output is selected.

**Comment by victorhuangwq** [comment]
Removed download file for autograder output
image

Shows download file properly with normal files
image

**Review by fanpu — APPROVED** [review]
Thanks for adding the fix!

**Pull request merged**
