### PR TITLE
Metrics Feature, Part of the Autolab Dashboard

### PR DESCRIPTION
**Pull request by victorhuangwq**
## Description

This PR contains the work from the metrics-feature branch, where the Autolab developed the metrics feature on the dashboard. 

Below is the introduction from the metrics documentation

> Traditional approaches of identifying students who are
> struggling with class is reactive; course staff wait for students to come to them to provide help, which can often be too late. 
> 
> The metrics feature seeks to be an proactive approach by actively identifying students who might be struggling in class through tracking of metrics that signify possible risks. Identifying at-risk students early would provide a better chance of getting them back on track in the course.

image

image

image

## How Has This Been Tested?

This PR has been tested as part of the other individual pull requests to the metrics-feature branch. This PR is meant to have a documentation of the merger from the metrics-feature branch into the master branch, as well to ensure that there are no merging issues. Done by ensuring that the code compiles and the the rails server can be served accordingly.

Further testing on the feature's exact implementation will be done later.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Comment by victorhuangwq** [comment]
@fanpu what are your opinions on how we should merge this feature in master? I would definitely like to keep all the commit history, and would not liked them to be squashed. However, do you think we should rebase or just merge?

**Comment by fanpu** [comment]
Rebasing would be nicer since the history of this feature will all be contiguous, although if there are major conflicts they may get quite annoying to resolve as every rebased commit may result in a conflict. However that usually only happens when you rename previously used variables, or rename files.

**Comment by victorhuangwq** [comment]
@fanpu but after I rebased on the master, it seemed as if all the commits happened when I rebased?

**Comment by fanpu** [comment]
Yup, that is correct!

**Review by fanpu — APPROVED** [review]
LGTM, great work team!

**Pull request merged**
