### PR TITLE
Started using rack-ssl-enforcer gem for forcing SSL

### PR DESCRIPTION
**Pull request by icanberk**

### CODE REVIEW

**Comment by icanberk** [comment]
This gem in general provides us with more flexibility.

**Comment by dlbucci** [comment]
How well has this been tested?

**Comment by icanberk** [comment]
Pretty well tested on sawshark. Although we might need to change some apache configs after pulling to milkshark.

**Comment by dlbucci** [comment]
We will.  We were using this gem before though?

**Comment by icanberk** [comment]
No we never used it before

**Comment by dlbucci** [comment]
So can we test this gem?

**Comment by icanberk** [comment]
I tested on sawshark.

**Pull request merged**
