### PR TITLE
Bug fixes and enhancements for github oauth2

### PR DESCRIPTION
**Pull request by fanpu**
## Description
Fixes the following bugs:

1. Proper error handling if user cancels OAuth flow

Adds the following enhancements:
1. Checks repository size before cloning it 

*NOTE*: please rollback db/migrate/20210929220050_create_github_integrations.rb (perform `rails db rollback` until the specific migration is rolled back, or do `rails db:rollback STEP=2`  if  there are 2 migrations to rollback), since I updated it to enforce uniqueness of user ID on github integrations as an additional layer of data consistency checks

## How Has This Been Tested?
1. If user submits a large repo, the repo will not be cloned and instead user will get a message that repo size is too large
2. If user cancels OAuth flow, user gets redirected to homepage instead of causing an internal server error

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Comment by cg2v** [comment]
GithubIntegration.clone_repo does not clean up its temporary files.

It might be easier to use [git archive](https://git-scm.com/docs/git-archive) instead of doing separate clone and tar tasks.

**Comment by cg2v** [comment]
AssessmentHandin:handin appears to accept github handins even if github submission is not enabled for the assessment. I can't tell for sure that this is not handled at a higher layer, but it's not good enough for the form to not offer github. The handin handler has to reject it too if not allowed..

**Comment by cg2v** [comment]
AssessmentHandin:handin needs to sanitize `params[:repo]`, as it is passed to `system`. In particular, it should not contain control characters, spaces or ;, but ideally, you should check it for alphanumeric, plus . - _ and /

**Review by ashleyzhang — APPROVED** [review]

**Comment by fanpu** [comment]
@cg2v Thanks for your comments, we will resolve them on the main branch (`oauth2-gh`)!

**Pull request merged**
