### PR TITLE
Add GitHub Configuration Tab to Configure Autolab

### LINKED ISSUE #1844: Add GitHub token configuration under Autolab Configure

### PR DESCRIPTION
**Pull request by victorhuangwq**
## Description

Adds a GitHub Configuration Tab to Configure Autolab

image

## Motivation and Context

Resolves #1844, as part of Autolab 3.0

## How Has This Been Tested?

1. Followed https://docs.autolabproject.com/installation/github_integration/ to register a new GitHub application. Registering it on localhost worked for me for local testing
image
2. Run autolab on port 80, so that http://localhost works
3. Add configuration detail to GitHub Client Settings in GitHub Integration.
4. It should then reflect that `Autolab is connected to Github!`

**submitting using Github** Go to a lab assessment, click on Github to try and submit via github
1. Click Connect To GitHub.
2. Connect to GitHub, follow the authorization steps.
3. 
image

**revoking github token**
1. Go to User > Account (or if you are admin, go to http://localhost/users/1)
2. Click on Revoke Github token
3. You should get a flash that you have successfully revoke the token

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required

If unsure, feel free to submit first and we'll help you along.

### CODE REVIEW

**Review by najclark — CHANGES_REQUESTED** [review]
Confirmed testing steps work 
image

image
Client ID and Client Secret aren't preserved in the form. It seems intentional for Client Secret but unintentional for Client ID. Not sure what the reason for hiding the Client Secret is, but could we just use a password field instead and still populate the value?

**Comment by victorhuangwq** [comment]
should be addressed
image

**Review by najclark — COMMENTED** [review]
lgtm

**Review by najclark — APPROVED** [review]
lgtm

**Pull request merged**
